apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-cluster-nginx
spec:
  destination:
    namespace: nginx
    name: dev-cluster
  project: dev-cluster-nginx
  source:
    path: nginx
    repoURL: https://github.com/lcostea/argocd-deploys.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
